# Generated by Django 2.0.3 on 2018-04-01 14:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0002_archive_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveSegment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('raw', 'Raw'), ('cloud', 'Cloud'), ('statistics', 'Statistics'), ('images', 'Images'), ('map', 'Map'), ('search', 'Search')], max_length=10)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('stop_time', models.DateTimeField(null=True)),
                ('archive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='archive.Archive')),
            ],
        ),
    ]
